packages:
  - "playground"
  - "multi-views"
  - "camera-controls"
  - "render-targets"
  - "post-processing"
  - "theatre"
  - "optimization"
  - "basic-shader"
  - "shaping"
  - "image-slider"
  - "water-shader"
  - "shader-transitions"
  - "vfx-stars"
  - "vfx-trails"
  - "vfx-engine"
  - "vfx-fireworks"
  - "vfx-wizard-game"
  - "webgpu-tsl"
  - "gpgpu-tsl"
