packages:
  - "playground"
  - "multi-views"
  - "camera-controls"
  - "render-targets"
  - "post-processing"
  - "theatre"
  - "optimization"
  - "basic-shader"
  - "shaping"
  - "image-slider"
  - "water-shader"
  - "shader-transitions"
