/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  MeshTransmissionMaterial,
  useDetectGPU,
  useGLTF,
  useScroll,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import type { Group, Mesh } from "three";

interface WawaCoinProps {
  transmissionSettings: any;
  scale: number;
}

export function WawaCoin({ transmissionSettings, ...props }: WawaCoinProps) {
  const { nodes, materials } = useGLTF("models/WawaCoin.glb");

  const data = useScroll();
  const ref = useRef<Group>(null);
  useFrame((_, delta) => {
    if (ref.current) {
      const rotSpeed = Math.max(1, (1 - data.curve(1 / 4, 1 / 4)) * 3);
      ref.current.rotation.z += rotSpeed * delta;
    }
  });
  const { tier, isMobile } = useDetectGPU();

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Circle as Mesh).geometry}
        material={materials.glass}
      >
        {tier !== 0 && !isMobile && (
          <MeshTransmissionMaterial
            {...transmissionSettings}
            toneMapped={false}
          />
        )}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Text as Mesh).geometry}
        material={materials["logo"]}
        position={[0, 0.088, 0.069]}
        scale={0.483}
      />
    </group>
  );
}

useGLTF.preload("models/WawaCoin.glb");
