/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Ninja_Male_Hair.gltf -o src/components/NinjaMale.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useEffect, useRef } from "react";
import type { Group, Mesh, SkinnedMesh } from "three";

interface NinjaMaleProps {
  envMapIntensity?: number;
  scale?: number;
}

export function NinjaMale({
  envMapIntensity = 0.3,
  scale = 0.1,
  ...props
}: NinjaMaleProps) {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/Ninja_Male_Hair.gltf"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (!actions["Run"]) return;
    actions["Run"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Bone} />
          <group name="Body_1">
            <skinnedMesh
              name="Cube004"
              geometry={(nodes.Cube004 as Mesh).geometry}
              material={materials.Skin}
              skeleton={(nodes.Cube004 as SkinnedMesh).skeleton}
            />
            <skinnedMesh
              name="Cube004_1"
              geometry={(nodes.Cube004_1 as Mesh).geometry}
              material={materials.Main}
              skeleton={(nodes.Cube004_1 as SkinnedMesh).skeleton}
            />
            <skinnedMesh
              name="Cube004_2"
              geometry={(nodes.Cube004_2 as Mesh).geometry}
              material={materials.Details}
              skeleton={(nodes.Cube004_2 as SkinnedMesh).skeleton}
            />
            <skinnedMesh
              name="Cube004_3"
              geometry={(nodes.Cube004_3 as Mesh).geometry}
              material={materials.Grey}
              skeleton={(nodes.Cube004_3 as SkinnedMesh).skeleton}
            />
            <skinnedMesh
              name="Cube004_4"
              geometry={(nodes.Cube004_4 as Mesh).geometry}
              material={materials.Face}
              skeleton={(nodes.Cube004_4 as SkinnedMesh).skeleton}
            />
            <skinnedMesh
              name="Cube004_5"
              geometry={(nodes.Cube004_5 as Mesh).geometry}
              material={materials.Hair}
              skeleton={(nodes.Cube004_5 as SkinnedMesh).skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Ninja_Male_Hair.gltf");
